[package]
name = "diffenator3"
version = "0.1.0"
edition = "2021"


[profile.release]
opt-level = "z"
lto = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rayon = { version = "*" }
indicatif = {version = "*", features = ["rayon"] }
thread_local = "1.1"
tera = "1"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2.63" }
console_error_panic_hook = { version = "0.1.6" }
wee_alloc = { version = "0.4.5" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "diffenator3"
path = "src/bin/diffenator3.rs"

[[bin]]
name = "ttj"
path = "src/bin/ttj.rs"

[dependencies]
cfg-if = "1.0.0"
clap = "4.4.7"
read-fonts = "0.13.0"
font-types = "0.4.0"
skrifa = "0.12.0"
serde_json = { version = "1.0.96", features = ["preserve_order"] }
serde = { version = "*", features = ["derive"] }
indexmap = "1.9.3"
ab_glyph = "0.2.21"
image = "0.24.6"
rustybuzz = "*"
ucd = "0.1.1"
unicode_names2 = "0.6.0"
unicode-character-database = "0.1.0"
