// AUTO-GENERATED by typescript-type-def

export type JSONValue = (null | boolean | number | string | (JSONValue)[] | {
    [key:string]:JSONValue;
});
export type Usize = number;

/**
 * A plain-language summary of the static difference signature.
 */
export type SignatureSummary = {

    /**
     * Number of cmap-matched glyphs that differ in outline or advance width.
     */
    "changed_glyphs": Usize;

    /**
     * Number of cmap-matched glyphs that are identical everywhere.
     */
    "identical_glyphs": Usize;

    /**
     * Encoded glyphs present only in the "before" font's cmap.
     */
    "missing_glyphs": (string)[];

    /**
     * Encoded glyphs present only in the "after" font's cmap.
     */
    "new_glyphs": (string)[];

    /**
     * Number of glyphs whose correspondence could not be established.
     */
    "uncertain_glyphs": Usize;

    /**
     * Number of GPOS single-adjustment (lookup type 1) differences.
     */
    "single_adjustments": Usize;

    /**
     * Number of GPOS pair-adjustment (lookup type 2 / kerning) differences.
     */
    "pair_adjustments": Usize;

    /**
     * Number of GPOS mark-attachment (lookup types 4/5/6) differences.
     */
    "mark_adjustments": Usize;

    /**
     * Number of GPOS cursive-attachment (lookup type 3) differences.
     */
    "cursive_adjustments": Usize;

    /**
     * Whether either font has contextual GPOS that isn't modelled.
     */
    "positioning_unmodelled": boolean;

    /**
     * Whether either font has contextual GSUB that isn't modelled by the
     * unencoded-glyph trace.
     */
    "gsub_unmodelled": boolean;

    /**
     * Whether the fonts share no cmap codepoints, making matching unreliable.
     */
    "mapping_failed": boolean;

    /**
     * Human-readable designspace locations where changes were recorded.
     */
    "changed_locations": (string)[];

    /**
     * A one-line plain-language overview.
     */
    "overview": string;

    /**
     * Plain-language bullet points describing the changes.
     */
    "points": (string)[];
};
export type EncodedGlyph = {

    /**
     * The character, as a string
     */
    "string": string;

    /**
     * Name of the character from the Unicode database, if available
     */
    "name"?: string;
};

/**
 * Represents changes to the cmap table - added or removed glyphs
 */
export type CmapDiff = {
    "missing"?: (EncodedGlyph)[];
    "new"?: (EncodedGlyph)[];
};
export type F32 = number;
export type LanguageDiff = {

    /**
     * Support level for font A
     */
    "level_a": string;

    /**
     * Support score for font A
     */
    "score_a": F32;

    /**
     * Number of fixes required for font A
     */
    "fixes_a": Usize;

    /**
     * Support level for font B
     */
    "level_b": string;

    /**
     * Support score for font B
     */
    "score_b": F32;

    /**
     * Number of fixes required for font B
     */
    "fixes_b": Usize;
};

/**
 * Represents a difference between two encoded glyphs
 */
export type GlyphDiff = {

    /**
     * The string representation of the glyph
     */
    "string": string;

    /**
     * The Unicode name of the glyph
     */
    "name": string;

    /**
     * The Unicode codepoint of the glyph
     */
    "unicode": string;

    /**
     * The number of differing pixels
     */
    "differing_pixels": Usize;

    /**
     * The font variation location applied to the glyph, if any
     */
    "location"?: string;
};

/**
 * Represents a difference between two renderings, whether words or glyphs
 */
export type Difference = {

    /**
     * The text string which was rendered
     */
    "word": string;

    /**
     * A string representation of the shaped buffer in the first font
     */
    "buffer_a": string;

    /**
     * A string representation of the shaped buffer in the second font, if different
     */
    "buffer_b"?: string;

    /**
     * The number of differing pixels
     */
    "differing_pixels": Usize;

    /**
     * The OpenType features applied to the text
     */
    "ot_features"?: string;

    /**
     * The OpenType language tag applied to the text
     */
    "lang"?: string;

    /**
     * The font variation location applied to the text, if any
     */
    "location"?: string;
};
export type LocationResult = {

    /**
     * Name of the location in designspace (named instance, or stringified coordinates)
     */
    "location": string;

    /**
     * Coordinates of the location in designspace
     */
    "coords"?: Record<string, F32>;

    /**
     * An error message, if something went wrong
     */
    "error"?: string;

    /**
     * Differences between glyphs
     */
    "glyphs"?: (GlyphDiff)[];

    /**
     * Differences between words
     */
    "words"?: Record<string, (Difference)[]>;
};
export type Report = {
    "tables"?: JSONValue;
    "signature_summary"?: SignatureSummary;
    "cmap_diff"?: CmapDiff;
    "languages"?: Record<string, LanguageDiff>;
    "locations"?: (LocationResult)[];
};
