import type { GlyphDiff, LocationResult } from "./api.js";
import type { SimpleCommand } from "./types.js";

// The generated wasm-bindgen module (pkg/diffenator3_web.js) is regenerated by
// wasm-pack whenever the Rust crate changes, so we don't rely on its generated
// .d.ts. Instead we declare the slice of the API this worker uses. This keeps
// the worker compiling even when the checked-in pkg/ output is stale.
interface WasmApi {
  debugging(): void;
  axes(font_a: Uint8Array, font_b: Uint8Array): string;
  diff_tables(
    font_a: Uint8Array,
    font_b: Uint8Array,
    f: (r: string) => void,
  ): void;
  diff_kerns(
    font_a: Uint8Array,
    font_b: Uint8Array,
    f: (r: string) => void,
  ): void;
  cmap_diff(
    font_a: Uint8Array,
    font_b: Uint8Array,
    f: (r: string) => void,
  ): void;
  diff_languages(
    font_a: Uint8Array,
    font_b: Uint8Array,
    f: (r: string) => void,
  ): void;
  modified_glyphs(
    font_a: Uint8Array,
    font_b: Uint8Array,
    location: string,
    f: (glyphs: string) => void,
  ): void;
  diff_words(
    font_a: Uint8Array,
    font_b: Uint8Array,
    custom_words: string[],
    location: string,
    f: (words: string) => void,
  ): void;
  diff_all(
    font_a: Uint8Array,
    font_b: Uint8Array,
    custom_words: string[],
    f: (all: string) => void,
  ): void;
  auto_words(location: string, f: (words: string) => void): void;
  use_auto_by_default(
    font_a: Uint8Array,
    font_b: Uint8Array,
    f: (auto: boolean) => void,
  ): void;
}

var module =
  import("../../pkg/diffenator3_web.js") as unknown as Promise<WasmApi>;

async function init() {
  let wasm = await module;
  self.postMessage({ type: "ready" });
  wasm.debugging();
  let commands = {
    tables: wasm.diff_tables,
    kerns: wasm.diff_kerns,
    cmap_diff: wasm.cmap_diff,
    languages: wasm.diff_languages,
  };

  self.onmessage = async (event) => {
    const { command, beforeFont, location, afterFont, customWords, token } =
      event.data;

    let simpleWasmDiff = (command: SimpleCommand) => {
      let post = (result: string) => {
        self.postMessage({
          type: command,
          [command]: JSON.parse(result)[command],
        });
      };
      commands[command](beforeFont, afterFont, post);
    };

    if (command == "axes") {
      let obj = JSON.parse(wasm.axes(beforeFont, afterFont));
      obj["type"] = "axes";
      self.postMessage(obj);
    } else if (
      command == "tables" ||
      command == "kerns" ||
      command == "cmap_diff" ||
      command == "languages"
    ) {
      simpleWasmDiff(command);
    } else if (command == "auto_default") {
      wasm.use_auto_by_default(beforeFont, afterFont, (auto) => {
        self.postMessage({ type: "auto_default", auto });
      });
    } else if (command == "modified_glyphs") {
      wasm.modified_glyphs(
        beforeFont,
        afterFont,
        location,
        (glyphs: string) => {
          self.postMessage({
            type: "modified_glyphs",
            modified_glyphs: JSON.parse(glyphs)[
              "modified_glyphs"
            ] as GlyphDiff[],
            token,
          });
        },
      );
    } else if (command == "words") {
      wasm.diff_words(
        beforeFont,
        afterFont,
        customWords,
        location,
        (words: string) => {
          self.postMessage({
            type: "words",
            words: JSON.parse(words)["words"],
            token,
          });
        },
      );
    } else if (command == "diff_all") {
      wasm.diff_all(beforeFont, afterFont, customWords, (payload: string) => {
        let obj = JSON.parse(payload);
        if (obj["kind"] == "summary") {
          self.postMessage({
            type: "diff_summary",
            summary: obj["summary"],
          });
        } else if (obj["kind"] == "locations") {
          self.postMessage({
            type: "diff_locations",
            locations: obj["locations"] as LocationResult[],
          });
        } else if (obj["kind"] == "glyphs") {
          self.postMessage({
            type: "diff_glyphs",
            locations: obj["locations"] as LocationResult[],
          });
        }
      });
    } else if (command == "auto_words") {
      // On-demand word diff for a single location, using the signature and
      // fonts stashed by the most recent diff_all call.
      wasm.auto_words(location, (payload: string) => {
        let obj = JSON.parse(payload);
        self.postMessage({
          type: "auto_words",
          location,
          words: obj["words"],
        });
      });
    }
  };
  return self;
}

init();
