[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# treat the project as a Rust binary application: https://www.maturin.rs/bindings#bin
bindings = "bin"

[project]
name = "diffenator3"