[package]
name = "ttj"
version = "0.1.0"
edition = "2021"

[dependencies]
diffenator3-lib = { path = "../diffenator3-lib" }
read-fonts = { workspace = true }
serde_json = { workspace = true }
clap = "*"
