[package]
name = "ttj"
version = "0.1.0"
edition = "2021"

[dependencies]
skrifa = { workspace = true }
read-fonts = { workspace = true }
serde_json = { workspace = true }
clap = "*"
indexmap = { workspace = true }
