use harfrust::{script, Direction, Script};
use static_lang_word_lists::WordList;
use std::sync::LazyLock;

pub(crate) fn get_wordlist(script: &str) -> Option<&LazyLock<WordList>> {
    let wl = match script {
        "Adlam" => &static_lang_word_lists::DIFFENATOR_ADLAM,
        "Arabic" => &static_lang_word_lists::DIFFENATOR_ARABIC,
        "Armenian" => &static_lang_word_lists::DIFFENATOR_ARMENIAN,
        "Avestan" => &static_lang_word_lists::DIFFENATOR_AVESTAN,
        "Bengali" => &static_lang_word_lists::DIFFENATOR_BENGALI,
        "Bopomofo" => &static_lang_word_lists::DIFFENATOR_BOPOMOFO,
        "Canadian_Aboriginal" => &static_lang_word_lists::DIFFENATOR_CANADIAN_ABORIGINAL,
        "Chakma" => &static_lang_word_lists::DIFFENATOR_CHAKMA,
        "Cherokee" => &static_lang_word_lists::DIFFENATOR_CHEROKEE,
        "Common" => &static_lang_word_lists::DIFFENATOR_COMMON,
        "Cyrillic" => &static_lang_word_lists::DIFFENATOR_CYRILLIC,
        "Devanagari" => &static_lang_word_lists::DIFFENATOR_DEVANAGARI,
        "Ethiopic" => &static_lang_word_lists::DIFFENATOR_ETHIOPIC,
        "Georgian" => &static_lang_word_lists::DIFFENATOR_GEORGIAN,
        // "Grantha" => &static_lang_word_lists::DIFFENATOR_GRANTHA,
        "Greek" => &static_lang_word_lists::DIFFENATOR_GREEK,
        "Gujarati" => &static_lang_word_lists::DIFFENATOR_GUJARATI,
        "Gurmukhi" => &static_lang_word_lists::DIFFENATOR_GURMUKHI,
        "Hebrew" => &static_lang_word_lists::DIFFENATOR_HEBREW,
        "Hiragana" => &static_lang_word_lists::DIFFENATOR_HIRAGANA,
        "Japanese" => &static_lang_word_lists::DIFFENATOR_JAPANESE,
        // "Kannada" => &static_lang_word_lists::DIFFENATOR_KANNADA,
        "Katakana" => &static_lang_word_lists::DIFFENATOR_KATAKANA,
        "Khmer" => &static_lang_word_lists::DIFFENATOR_KHMER,
        "Lao" => &static_lang_word_lists::DIFFENATOR_LAO,
        "Latin" => &static_lang_word_lists::DIFFENATOR_LATIN,
        "Lisu" => &static_lang_word_lists::DIFFENATOR_LISU,
        "Malayalam" => &static_lang_word_lists::DIFFENATOR_MALAYALAM,
        "Mongolian" => &static_lang_word_lists::DIFFENATOR_MONGOLIAN,
        "Myanmar" => &static_lang_word_lists::DIFFENATOR_MYANMAR,
        "Ol_Chiki" => &static_lang_word_lists::DIFFENATOR_OL_CHIKI,
        "Oriya" => &static_lang_word_lists::DIFFENATOR_ORIYA,
        "Osage" => &static_lang_word_lists::DIFFENATOR_OSAGE,
        "Sinhala" => &static_lang_word_lists::DIFFENATOR_SINHALA,
        "Syriac" => &static_lang_word_lists::DIFFENATOR_SYRIAC,
        "Tamil" => &static_lang_word_lists::DIFFENATOR_TAMIL,
        "Telugu" => &static_lang_word_lists::DIFFENATOR_TELUGU,
        "Thai" => &static_lang_word_lists::DIFFENATOR_THAI,
        "Thanaa" => &static_lang_word_lists::DIFFENATOR_THANAA,
        "Tibetan" => &static_lang_word_lists::DIFFENATOR_TIBETAN,
        "Tifinagh" => &static_lang_word_lists::DIFFENATOR_TIFINAGH,
        "Vai" => &static_lang_word_lists::DIFFENATOR_VAI,

        _ => return None,
    };
    Some(wl)
}

pub fn get_script_tag(script: &str) -> Option<Script> {
    match script {
        "Adlam" => Some(script::ADLAM),
        "Arabic" => Some(script::ARABIC),
        "Armenian" => Some(script::ARMENIAN),
        "Avestan" => Some(script::AVESTAN),
        "Bengali" => Some(script::BENGALI),
        "Bopomofo" => Some(script::BOPOMOFO),
        "Canadian_Aboriginal" => Some(script::CANADIAN_SYLLABICS),
        "Chakma" => Some(script::CHAKMA),
        "Cherokee" => Some(script::CHEROKEE),
        "Common" => Some(script::COMMON),
        "Cyrillic" => Some(script::CYRILLIC),
        "Devanagari" => Some(script::DEVANAGARI),
        "Ethiopic" => Some(script::ETHIOPIC),
        "Georgian" => Some(script::GEORGIAN),
        "Grantha" => Some(script::GRANTHA),
        "Greek" => Some(script::GREEK),
        "Gujarati" => Some(script::GUJARATI),
        "Gurmukhi" => Some(script::GURMUKHI),
        "Hebrew" => Some(script::HEBREW),
        "Hiragana" => Some(script::HIRAGANA),
        "Kannada" => Some(script::KANNADA),
        "Katakana" => Some(script::KATAKANA),
        "Khmer" => Some(script::KHMER),
        "Lao" => Some(script::LAO),
        "Latin" => Some(script::LATIN),
        "Lisu" => Some(script::LISU),
        "Malayalam" => Some(script::MALAYALAM),
        "Mongolian" => Some(script::MONGOLIAN),
        "Myanmar" => Some(script::MYANMAR),
        "Ol_Chiki" => Some(script::OL_CHIKI),
        "Oriya" => Some(script::ORIYA),
        "Osage" => Some(script::OSAGE),
        "Sinhala" => Some(script::SINHALA),
        "Syriac" => Some(script::SYRIAC),
        "Tamil" => Some(script::TAMIL),
        "Telugu" => Some(script::TELUGU),
        "Thai" => Some(script::THAI),
        "Tibetan" => Some(script::TIBETAN),
        "Tifinagh" => Some(script::TIFINAGH),
        "Vai" => Some(script::VAI),
        _ => None,
    }
}

pub fn get_script_direction(script: &str) -> Direction {
    match script {
        "Arabic" => Direction::RightToLeft,
        "Avestan" => Direction::RightToLeft,
        "Hebrew" => Direction::RightToLeft,
        "Syriac" => Direction::RightToLeft,
        "Thanaa" => Direction::RightToLeft,
        _ => Direction::LeftToRight,
    }
}
